### ISSUE TITLE
Google (not Oxford English dictionary)

### ISSUE THREAD

**Issue by grahamperrin** [smoqadam/oxford-dictionary-browser-addon#2]
As far as I can tell, from the code of the extension, there's use of Google e.g.. https://dict.smoqadam.me/

https://addons.mozilla.org/addon/oxford-dictionary-addon/ describes use of the Oxford English dictionary. Is this misleading? 

Consider https://www.oed.com/

**Comment by smoqadam** [comment]
Hi, 

no, I'm using this project https://github.com/smoqadam/oxfordDictionaryApi which it's using https://www.lexico.com/en.

Thanks

**Comment by grahamperrin** [comment]
http://googlesystem.blogspot.com/search/label/Google%20Dictionary there's mention of Oxford Dictionary (not to be confused with Oxford English Dictionary). 

http://oxforddictionaries.com/ redirects to https://languages.oup.com/ with 

> **Our English and Spanish dictionaries have now moved to Lexico.com.**

– and so on.

**Comment by grahamperrin** [comment]
Ah, comments crossed paths …

**Comment by grahamperrin** [comment]
https://github.com/smoqadam/english-learners-dictionary/commit/b83898e0c05265616818d9acee7c141bd266efe7 and https://github.com/smoqadam/english-learners-dictionary/commit/13c9e9e9d6eda5b18051c5f321d8f39797210a8e noted with thanks. 

https://addons.mozilla.org/addon/oxford-dictionary-addon/ no longer found. 

Update to *English Learner's Dictionary* version 1.4 gained in Waterfox Classic. 

Found: 

* https://addons.mozilla.org/addon/english-learners-dictionary/

Thank you!
