### ISSUE TITLE
English Learner's Dictionary 1.5 versus new Reddit

### ISSUE THREAD

**Issue by grahamperrin** [smoqadam/oxford-dictionary-browser-addon#6]
### Home-built Waterfox Classic 2019.12 (20191210201058)

Extension enabled: 

![image](https://user-images.githubusercontent.com/192271/71536803-45c2e100-290b-11ea-8877-c8f6ec0e3d5e.png)

Disabled: 

![image](https://user-images.githubusercontent.com/192271/71536825-8589c880-290b-11ea-9957-c18d1753e781.png)

### Firefox 71.0

Screen recording: 

* `2019-12-28 00:36.mp4` https://put.re/player/7iTdAdW5.mp4
* [2019-12-28 00:36.zip](https://github.com/smoqadam/english-learners-dictionary/files/4006548/2019-12-28.00.36.zip)

**Comment by smoqadam** [comment]
Thanks for the report. I fixed it and published it. The new version should fix the problem.

**Comment by grahamperrin** [comment]
Fix confirmed. Thanks!
